### ISSUE TITLE
runtime: docker big scaling gql backend crash proxy

### ISSUE THREAD

**Issue by fasibio** [fasibio/GraphqlDockerProxy#2]
By fast scaling from one to 15 swapi server, the app crashed.
By slow scaling it works fine. (1 to 5, 5 to 7, 7 to 11, 11 to 13, 13 to 15)

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ECONNREFUSED 172.19.0.8:9000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

**Comment by fasibio** [comment]
kubernetes does not have this problem because the service layer
